name: Vault-Sync
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install axios
      - env:
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          LEETCODE_CSRF_TOKEN: ${{ secrets.LEETCODE_CSRF_TOKEN }}
        run: node sync.js
      - run: |
          git config --global user.name "BLACK-BOT"
          git config --global user.email "bot@black0x80.io"
          git add .
          git commit -m "Vault sync: $(date +'%Y-%m-%d')" || exit 0
          git push
